TechStoreGen2/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TechStoreGen2.Models;
using TechStoreGen2.ViewModels;

namespace TechStoreGen2.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private ICart cart;

        public CartController(IProductRepository repo, ICart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId,
                string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

TechStoreGen2/Controllers/OrderController.cs
using AutoMapper;
using Login.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TechStoreGen2.Models;

namespace TechStoreGen2.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private ICart cart;
        private IMapper mapper;
        public OrderController(IOrderRepository repoService, ICart cartService, IMapper mapp)
        {
            repository = repoService;
            cart = cartService;
            mapper = mapp;
        }

        [Authorize]
        public ViewResult List() =>
            View(repository.Orders.Where(x => !x.Shipped));

        [HttpPost]
        [Authorize]
        public IActionResult MarkShipped(int orderID)
        {
            Order order = repository.Orders.FirstOrDefault(x => x.OrderID == orderID);
            if(order != null)
            {
                order.Shipped = true;
                repository.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }

        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }

        public IActionResult Create(OrderViewModel order)
        {
            if (ModelState.IsValid)
            {
                repository.SaveOrder(mapper.Map<OrderViewModel, Order>(order));
                TempData["message"] = $"{order.Name} has been created";
                return RedirectToAction("Index", "Admin");
            }
            return RedirectToAction("Index", "Admin");
        }

        public IActionResult Edit(OrderViewModel order)
        {
            if (ModelState.IsValid)
            {
                var editedOrder = repository.Orders.FirstOrDefault(i => i.OrderID == order.OrderID);
                editedOrder.Name = order.Name;
                editedOrder.City = order.City;
                editedOrder.Country = order.Country;
                editedOrder.GiftWrap = order.GiftWrap;
                editedOrder.Line1 = order.Line1;
                editedOrder.Line2 = order.Line2;
                editedOrder.Line3 = order.Line3;
                editedOrder.State = order.State;
                editedOrder.Zip = order.Zip;
                repository.SaveOrder(editedOrder);
                TempData["message"] = $"{editedOrder.Name} has been saved";
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                return View(order);
            }
        }

        public IActionResult Delete(int orderID)
        {
            Order deletedOrder = repository.DeleteOrder(orderID);
            if (deletedOrder != null)
            {
                TempData["message"] = $"{deletedOrder.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

TechStoreGen2/Views/Shared/ProductSummary.cshtml
@using TechStoreGen2.Models 

@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small style="color:black">@Model.Price.ToString("C2")</small>
            </span>
        </h4>
    </div>

    <form id="@Model.ProductID" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductID" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.Path" />
        <span class="card-text p-1"></span>
        @Model.Description
        <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">Add To Cart</button>
    </form>
</div>

TechStoreGen2/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
</head>
<body class="m-1 р-1">
    <div class="bg-info p-2"><h4>@ViewBag.Title</h4></div>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js">
    </script>
    <script src="/liЬ/jquery-validation-unobtrusive/jquery.validate.unoЬtrusive.min.js">
    </script>
    <div class="bg-info р-2 row">
        <div class="col-2">
            <a asp-controller="Users" asp-action="Index" class="btn btn-primary">Users</a>
            <a asp-controller="Roles" asp-action="Index" class="btn btn-primary">Roles</a>
            <a asp-controller="Order" asp-action="List" class="btn btn-primary">Orders</a>
            <a asp-controller="Roles" asp-action="UserList" class="btn btn-primary">Roles for users</a>
            <a class="btn btn-primary" asp-action="Login" asp-controller="Account">Log Out</a>
        </div>
    </div>

    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

TechStoreGen2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="@Url.Content("~/Content/Style.css")" rel="stylesheet" type="text/css" />
    <style type="text/css">
        #checkoutForm {
            width: 300px;
        }

        .someClass {
            margin: auto;
        }

            .someClass > div {
                display: flex;
                justify-content: space-between;
                align-items: center;
                margin-bottom: 0;
            }

        .headerCheckout {
            text-align: center;
            margin: 10px auto;
        }

        #giftButton {
            margin: 10px auto;
        }

        label {
            font-size: 16px;
            font-weight: bold;
        }

        input {
            margin: 0;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="List">TechStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">             
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TechStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TechStoreGen2/Views/Shared/_ProductLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="List">TechStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-4 text-right">
                @await Component.InvokeAsync("CartSummary")
            </div>
        </div>
        <div class="row m-1 p-1">
            <div id="categories" class="col-3">
                @await Component.InvokeAsync("NavigationMenu")
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Login - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>